version: "3.8"
networks:
  app_network:
    driver: bridge
services:
  mongo:
    image: mongo:5.0.10

    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=297ugbT1DM
    container_name: mongodb
    ports:
      - "27017:27017"
    expose:
      - 27017
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local
